AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'spec/support/rails_test_app/**/*'

Style/Documentation:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

Style/EmptyMethod:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'zapata.gemspec'
