language: ruby

bundler_args: --without development

script: script/test
gemfile: spec/support/rails_test_app/Gemfile

rvm:
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby-head
  - rbx

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx

branches:
  only:
    - master
