language: ruby
script: script/test
rvm:
  - 2.3.8
  - 2.4.7
  - 2.5.6
  - 2.6.4
gemfile:
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile
matrix:
  exclude:
  - rvm: 2.3.8
    gemfile: gemfiles/6.0.gemfile
  - rvm: 2.4.7
    gemfile: gemfiles/6.0.gemfile